[package]
name = "bls"
version = "0.1.1"
authors = ["Doron <doronz@zengo.com>", "Omer <omer@zengo.com>"]
description = "threshold BLS library"
edition = "2018"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
curv = { git = "https://github.com/ZenGo-X/curv", tag = "v0.5.4"}
zeroize = "0.10"
rand = "0.7.3"
pairing-plus = "0.19"
ff-zeroize = "0.6.3"

[dev-dependencies]
criterion = "0.3.3"
bls_sigs_ref = "0.3.0"
sha2 = "0.8.0"

[lib]
crate-type = ["lib"]

[features]
# Internally used feature for testing purposes. You normally don't want to use it.
dev = []

[[bench]]
name = "criterion"
harness = false
required-features = ["dev"]
